let selectedMood="";let latestScore=0;let currentLang="en";
function showPage(pageId){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const t=document.getElementById(pageId);if(t)t.classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active-tab"));document.querySelectorAll("nav button").forEach(b=>{if(b.getAttribute("onclick")&&b.getAttribute("onclick").includes(pageId))b.classList.add("active-tab")});window.scrollTo(0,0)}
function toggleDarkMode(){document.body.classList.toggle("dark-mode");updateDarkButton()}
function updateDarkButton(){const btn=document.getElementById("darkBtn");btn.innerText=document.body.classList.contains("dark-mode")?(currentLang==="zh"?"☀️ 亮色":"☀️ Light"):(currentLang==="zh"?"🌙 深色":"🌙 Dark")}
function changeLanguage(){currentLang=document.getElementById("languageSelect").value;document.querySelectorAll("[data-en][data-zh]").forEach(item=>{item.innerHTML=item.getAttribute("data-"+currentLang)});document.querySelectorAll("[data-placeholder-en][data-placeholder-zh]").forEach(item=>{item.placeholder=item.getAttribute("data-placeholder-"+currentLang)});if(selectedMood!="")updateMoodText();if(latestScore>=0)updateStatistics(latestScore);updateDarkButton()}
function chooseMood(mood){selectedMood=mood;updateMoodText();document.getElementById("moodAdvice").innerText=getMoodAdvice(mood)}
function updateMoodText(){const text=currentLang==="zh"?"你今天的心情：":"Your mood today: ";document.getElementById("moodText").innerText=text+translateMood(selectedMood)}
function translateMood(mood){if(currentLang==="en")return mood;if(mood.includes("Happy"))return"開心 😊";if(mood.includes("Normal"))return"普通 😐";if(mood.includes("Sad"))return"難過 😢";if(mood.includes("Angry"))return"生氣 😠";if(mood.includes("Tired"))return"疲累 😴";if(mood.includes("Anxious"))return"焦慮 😟";return mood}
function getMoodAdvice(mood){if(currentLang==="zh"){if(mood.includes("Happy"))return"很好！保持正向能量，也可以把好心情分享給別人。";if(mood.includes("Normal"))return"普通也沒關係。試著做一件能讓自己變好的小事。";if(mood.includes("Sad"))return"感到難過是正常的。可以寫下心情，或找信任的人聊聊。";if(mood.includes("Angry"))return"先休息一下，慢慢呼吸，再做反應。";if(mood.includes("Tired"))return"休息很重要。記得喝水，今晚可以早點睡。";if(mood.includes("Anxious"))return"可以試試呼吸練習，並提醒自己你不是孤單的。"}else{if(mood.includes("Happy"))return"Great! Keep your positive energy and share it with others.";if(mood.includes("Normal"))return"That is okay. Try doing one small thing that makes you feel better.";if(mood.includes("Sad"))return"It is okay to feel sad. Try writing your feelings or talking to someone you trust.";if(mood.includes("Angry"))return"Take a short break. Breathe slowly before you react.";if(mood.includes("Tired"))return"Rest is important. Drink water and try to sleep earlier tonight.";if(mood.includes("Anxious"))return"Try the breathing exercise and remind yourself that you are not alone."}return""}
function calculateResult(){let score=0;for(let i=1;i<=5;i++){const a=document.querySelector('input[name="q'+i+'"]:checked');if(!a){alert(currentLang==="zh"?"請回答所有壓力測驗問題。":"Please answer all stress quiz questions.");showPage("quiz");return}score+=Number(a.value)}latestScore=score;const d=getResultData(score);const journal=document.getElementById("journalText").value;const grateful=document.getElementById("gratefulText").value;const goals=document.querySelectorAll(".goal:checked").length;const pct=score*10;document.getElementById("progressBar").style.width=pct+"%";document.getElementById("progressBar").innerText=pct+"%";const box=document.getElementById("resultBox");box.style.background=d.color;if(currentLang==="zh"){box.innerHTML=`<p><strong>心情：</strong> ${selectedMood?translateMood(selectedMood):"尚未選擇"}</p><p><strong>壓力分數：</strong> ${score} / 10</p><p><strong>壓力等級：</strong> ${d.level}</p><p><strong>建議：</strong> ${d.advice}</p><p><strong>支援提醒：</strong> ${d.support}</p><p><strong>日記：</strong> ${journal||"未填寫"}</p><p><strong>感謝事項：</strong> ${grateful||"未填寫"}</p><p><strong>完成目標：</strong> ${goals} / 5</p>`}else{box.innerHTML=`<p><strong>Mood:</strong> ${selectedMood||"Not selected"}</p><p><strong>Stress Score:</strong> ${score} / 10</p><p><strong>Stress Level:</strong> ${d.level}</p><p><strong>Advice:</strong> ${d.advice}</p><p><strong>Support Reminder:</strong> ${d.support}</p><p><strong>Journal:</strong> ${journal||"No journal written."}</p><p><strong>Grateful For:</strong> ${grateful||"Not written."}</p><p><strong>Goals Completed:</strong> ${goals} / 5</p>`}updateStatistics(score);showPage("result")}
function getResultData(score){if(currentLang==="zh"){if(score<=3)return{level:"低壓力",advice:"你目前狀態不錯，繼續保持並照顧好自己。",support:"保持健康作息，並持續關心自己的心情。",color:"#c8e6c9"};if(score<=6)return{level:"中等壓力",advice:"可以休息一下、喝水、聽音樂，或到外面走走。",support:"可以嘗試呼吸練習。如果壓力持續，建議找信任的人聊聊。",color:"#fff59d"};return{level:"高壓力",advice:"試著深呼吸，並和信任的朋友、老師、家人或輔導老師談談。",support:"請查看幫助中心。如果你覺得不安全，請立刻撥打緊急電話。",color:"#ffcdd2"}}else{if(score<=3)return{level:"Low Stress",advice:"You are doing well. Keep going and take care of yourself.",support:"Keep a healthy routine and continue checking your mood.",color:"#c8e6c9"};if(score<=6)return{level:"Medium Stress",advice:"Take a short break, drink water, listen to music, or go outside for a walk.",support:"Try the breathing exercise. If stress continues, talk to someone you trust.",color:"#fff59d"};return{level:"High Stress",advice:"Try deep breathing and talk to a trusted friend, teacher, family member, or counselor.",support:"Please check the Help section. If you feel unsafe, call emergency support immediately.",color:"#ffcdd2"}}}
function updateStatistics(score){const pct=score*10;if(currentLang==="zh"){document.getElementById("statsMood").innerText="心情："+(selectedMood?translateMood(selectedMood):"尚未選擇");document.getElementById("statsScore").innerText="壓力分數："+score+" / 10"}else{document.getElementById("statsMood").innerText="Mood: "+(selectedMood||"Not selected");document.getElementById("statsScore").innerText="Stress Score: "+score+" / 10"}document.getElementById("statsBar").style.width=pct+"%";document.getElementById("statsBar").innerText=pct+"%"}
function submitFeedback(){const fb=document.getElementById("feedbackText").value;const box=document.getElementById("feedbackResult");if(fb.trim()===""){alert(currentLang==="zh"?"請先輸入你的回饋。":"Please write your feedback first.");return}box.classList.remove("hidden");box.innerHTML=currentLang==="zh"?`<h3>謝謝你的回饋！</h3><p>你的回饋：${fb}</p>`:`<h3>Thank you for your feedback!</h3><p>Your feedback: ${fb}</p>`;document.getElementById("feedbackText").value=""}
function restart(){location.reload()}
document.addEventListener("DOMContentLoaded",function(){showPage("home");changeLanguage()});
